### ISSUE TITLE
hpatch_evaluation.py use？

### ISSUE THREAD

**Issue by Penge666** [vignywang/AWDesc#5]
May I ask how this file was tested?

hpatch_evaluation.py

**Comment by vignywang** [comment]
This file was initially used to evaluate the model during training, but was discarded because we found that the metrics did not change much after the model converged, so we all used the model from the last epoch. Tests were performed using the HPatches-Sequences-Matching-Benchmark.ipynb file, which is consistent with methods such as d2net.

**Comment by Penge666** [comment]
Hello author, may I ask which code was used to run these tables in your paper?

![image](https://github.com/vignywang/AWDesc/assets/54142179/fd05f1e5-92f1-4bd6-a47d-7d831140106f)
![image](https://github.com/vignywang/AWDesc/assets/54142179/ab643885-aafb-4a77-b891-728de9f8b659)
thank you!
